---
title: "flat_read_sheet_triad.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# read_sheet_triad

```{r development-read_sheet_triad}
# Prepare the code of your function here
```

```{r function-read_sheet_triad}
#' Read Googlesheet Triad
#'
#' @return \code{read_sheet_triad} returns a tibble with triad information
#' @export
#' @importFrom googlesheets4 read_sheet
#'
#' @examples
read_sheet_triad <- function() {
  keysAPI <- get_config(env = "google")
  ss <- keysAPI[["base_url"]]
  sheet <- keysAPI[["triade_sheet"]]
  data <- googlesheets4::read_sheet(
    ss = ss,
    sheet = sheet
  )
  return(data)
}
```

```{r examples-read_sheet_triad}
triads <- read_sheet_triad()
```

```{r tests-read_sheet_triad}
test_that("read_sheet_triad works", {
  expect_true(inherits(read_sheet_triad, "function"))
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_read_sheet_triad.Rmd", vignette_name = "Read Googlesheet Triad")
```

