---
title: "flat_plot_tvc_network.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# plot_tvc_network

```{r development-plot_tvc_network}
# Prepare the code of your function here
```

```{r function-plot_tvc_network}
#' Plot tvc songs network
#'
#' @param data a tibble as returned by \code{\link{parse_triade}}
#'
#' @return \code{plot_tvc_network} returns a network plot
#' @export
#' @importFrom dplyr filter bind_rows mutate distinct full_join join_by rename group_by n arrange desc slice relocate select left_join summarise if_else
#' @importFrom ggnetwork ggnetwork geom_edges geom_nodes geom_nodetext theme_blank
#' @importFrom ggplot2 ggplot aes guides scale_linetype_manual labs scale_colour_manual theme element_rect element_blank
#' @importFrom igraph graph_from_data_frame V E nicely
#' @importFrom purrr map_lgl
#' @importFrom tibble tibble column_to_rownames
#' @importFrom tidyr unnest
#'
#' @examples
plot_tvc_network <- function(data) {
  data <- data %>% 
    dplyr::filter(!is.na(Degree),
                  triad == "1 7") %>% 
    dplyr::mutate(ISRC = dplyr::if_else(is.na(ISRC), Song, ISRC))
  #### Calcul des liens ####
  
  edges <- dplyr::bind_rows(
    ## Harmonie Sous-Jacente
    data %>%
      dplyr::filter(!is.na(`Harmonie Sous-Jacente`)) %>%
      dplyr::mutate(Group = paste("Harmonie sous-Jacente:", `Harmonie Sous-Jacente`)) %>%
      dplyr::distinct(ISRC, Group) %>%
      dplyr::full_join(x = ., y = .,
                       by = dplyr::join_by(Group),
                       relationship = "many-to-many",
                       suffix = c("_from", "_to")) %>%
      dplyr::rename(from = ISRC_from,
                    to = ISRC_to) %>%
      dplyr::filter(from != to),
    ## Degre de la note mediane
    data %>%
      dplyr::filter(!is.na(Degree)) %>%
      dplyr::mutate(Group = paste("Degr\u00e9 de la note m\u00e9diane:", Degree)) %>%
      dplyr::distinct(ISRC, Group) %>%
      dplyr::full_join(x = ., y = .,
                       by = dplyr::join_by(Group),
                       relationship = "many-to-many",
                       suffix = c("_from", "_to")) %>%
      dplyr::rename(from = ISRC_from,
                    to = ISRC_to) %>%
      dplyr::filter(from != to),
    ## Type / usage
    data %>%
      dplyr::filter(!is.na(Type)) %>%
      dplyr::mutate(Group = paste("Type:", Type)) %>%
      dplyr::distinct(ISRC, Group) %>%
      dplyr::full_join(x = ., y = .,
                       by = dplyr::join_by(Group),
                       relationship = "many-to-many",
                       suffix = c("_from", "_to")) %>%
      dplyr::rename(from = ISRC_from,
                    to = ISRC_to) %>%
      dplyr::filter(from != to),
    ## Mode Majeur/Mineur
    data %>%
      dplyr::filter(!is.na(Mode)) %>%
      ## Le groupe "Majeur" est encombrant
      dplyr::filter(!Mode %in% "Majeur") %>%
      dplyr::mutate(Group = paste("Mode:", Mode)) %>%
      dplyr::distinct(ISRC, Group) %>%
      dplyr::full_join(x = ., y = .,
                       by = dplyr::join_by(Group),
                       relationship = "many-to-many",
                       suffix = c("_from", "_to")) %>%
      dplyr::rename(from = ISRC_from,
                    to = ISRC_to) %>%
      dplyr::filter(from != to),
    ## Instrument = La Voix ou La Guitare
    data %>%
      dplyr::filter(!is.na(Instrument)) %>%
      ## Le groupe "Majeur" est encombrant
      dplyr::filter(Instrument %in% c("Vocals", "Muted Trumpet")) %>%
      dplyr::mutate(Group = paste("Instrument:", Instrument)) %>%
      dplyr::distinct(ISRC, Group) %>%
      dplyr::full_join(x = ., y = .,
                       by = dplyr::join_by(Group),
                       relationship = "many-to-many",
                       suffix = c("_from", "_to")) %>%
      dplyr::rename(from = ISRC_from,
                    to = ISRC_to) %>%
      dplyr::filter(from != to),
    ## Same Artist
    data %>%
      dplyr::filter(!is.na(Artist)) %>%
      ## Le groupe "Majeur" est encombrant
      dplyr::mutate(Group = paste("Artist:", Artist)) %>%
      dplyr::distinct(ISRC, Group) %>%
      dplyr::full_join(x = ., y = .,
                       by = dplyr::join_by(Group),
                       relationship = "many-to-many",
                       suffix = c("_from", "_to")) %>%
      dplyr::rename(from = ISRC_from,
                    to = ISRC_to) %>%
      dplyr::filter(from != to),
    ## Genre
    data %>%
      dplyr::rename(Genres = genres) %>%
      # dplyr::select(Genres) %>%
      ## Les triades etiquetees "Son Pop Loce 80's" sont forcement "Pop"
      # dplyr::mutate(`Parent Genres` = dplyr::if_else(is.na(`Parent Genres`) & is.na(`Genres`) & Type == "son pop love 80s",
      #                                                "Pop",
      #                                                `Parent Genres`)) %>%
      ## On rassemble Genre et Genre Parents
      # dplyr::mutate(Genres = paste(Genres, `Parent Genres`, sep = ", ")) %>%
      dplyr::filter(purrr::map_lgl(.x = Genres, .f =~ length(.x) > 0L)) %>%
      dplyr::distinct(ISRC, Genres) %>%
      tidyr::unnest(cols = Genres) %>%
      dplyr::rename(Genre = Genres) %>%
      ## On supprime les genres NA
      # dplyr::filter(!(is.na(Genre) | Genre == "NA")) %>%
      ## On supprime les Genres qui ne rassemble pas de chansons
      dplyr::group_by(Genre) %>%
      dplyr::mutate(Nb_Chansons = dplyr::n()) %>%
      dplyr::filter(dplyr::n() > 1L) %>%
      ## Garder le genre le plus evocateur pour une chansons (des genres sont redondants entre eux)
      dplyr::group_by(ISRC) %>%
      dplyr::arrange(dplyr::desc(Nb_Chansons)) %>%
      dplyr::slice(1) %>%
      dplyr::mutate(Group = paste("Genre:", Genre)) %>%
      dplyr::distinct(ISRC, Group) %>%
      dplyr::full_join(x = ., y = .,
                       by = dplyr::join_by(Group),
                       relationship = "many-to-many",
                       suffix = c("_from", "_to")) %>%
      dplyr::rename(from = ISRC_from,
                    to = ISRC_to) %>%
      dplyr::filter(from != to)
  ) %>%
    dplyr::relocate(Group, from, to)
  
  edges <- edges %>%
    dplyr::mutate(id = 1:dplyr::n())
  
  edges2 <- edges
  edges2$from <- edges$to
  edges2$to <- edges$from
  
  tmp <- dplyr::bind_rows(edges, edges2) %>%
    dplyr::group_by(Group, from, to) %>%
    dplyr::arrange(Group, from, to, id) %>%
    dplyr::slice(1)
  tmp$id %>% unique() %>% length()
  
  edges <- edges %>%
    dplyr::filter(id %in% tmp$id) %>%
    dplyr::select(-id)
  
  #### vertices and edges ####
  
  bands <- list(
    # Les sommets = les chansons
    "vertices" = tibble::tibble(ISRC = c(edges$from, edges$to)) %>%
      dplyr::distinct(ISRC) %>%
      ## Label et Size
      dplyr::left_join(dplyr::distinct(data, ISRC, Song, track.popularity, Affirmation),
                       by = dplyr::join_by(ISRC)) %>%
      dplyr::group_by(ISRC, Song) %>%
      dplyr::summarise(size = head(dplyr::if_else(is.na(track.popularity), 10, track.popularity), 1L) * max(as.numeric(Affirmation) / 5),
                       .groups = "drop") %>%
      dplyr::rename(label = Song) %>%
      dplyr::mutate(rownames = ISRC) %>%
      tibble::column_to_rownames(var = "rownames"),
    # Liens
    "edges" = edges
  )
  
  #### Main Grouping variables ####
  # mainGroups <- names(head(sort(table(bands$edges$Group), decreasing = TRUE), n = 6))
  ## Degrees
  mainGroups <- unique(grep(pattern = "^Degr", x = bands$edges$Group, value = TRUE))
  suffixGroup <- "Degre-note-mediane"
  ## Harmonie
  # mainGroups <- unique(grep(pattern = "^Harmonie", x = bands$edges$Group, value = TRUE))
  # suffixGroup <- "Harmonie-Sous-Jacente"
  
  #### Network plot ####
  fb.igra <- igraph::graph_from_data_frame(
    d = bands$edges[, c("from", "to")],
    directed = FALSE
  )
  igraph::V(fb.igra)$conf <- bands$vertices[igraph::V(fb.igra)$name, "label"]
  igraph::V(fb.igra)$size <- bands$vertices[igraph::V(fb.igra)$name, "size"]
  igraph::E(fb.igra)$Group <- bands$edges$Group
  # E(fb.igra)$Admin <- bands$edges$Admin
  # E(fb.igra)$lty=ifelse(E(fb.igra)$Admin == 1, 1, 2)
  
  #Tips: ctrl+shift+A to reformat
  set.seed(3212019)
  pggnetwork <- ggplot2::ggplot(
    ggnetwork::ggnetwork(# provide the underlying dataframe
      fb.igra, #input: network object
      layout = igraph::nicely()
    ),
    #can pass layout parameter
    ggplot2::aes(x, y, xend = xend, yend = yend)
  ) + #mapping for edges
    ggnetwork::geom_edges(ggplot2::aes(#linetype = as.factor(Admin),
      color = gsub(pattern = "Degr\u00e9 de la note m\u00e9diane: ", replacement = "", Group)),
      #arrow = arrow(length = unit(6, "pt"), type = "closed") #if directed
      # color = "grey50",
      data = function(x) { x[ x$Group %in% mainGroups, ]},
      curvature = 0.2,
      alpha = 0.5
    ) +
    ggnetwork::geom_nodes(ggplot2::aes(size = size),
                          # size = 3, color = conf
                          alpha=0.5) +
    ggnetwork::geom_nodes(fill = "#E74C3C", #"#D64545", "#C23B22", "red",
                          color = "black",
                          size = 5, shape = 21,
                          data = function(x) { x[ x$conf == "A Thousand Miles", ]}) +
    ggplot2::guides(alpha = "none") +
    ggnetwork::geom_nodetext(ggplot2::aes(label = insert_line_breaks_adaptive(conf)), # 1st occurence only
                             size = 2.5, nudge_y = .02)+
    # scale_color_brewer("Conference",
    #                    palette = "Paired") +
    ggplot2::scale_linetype_manual(values = c(2, 1)) +
    ggplot2::guides(linetype = "none",
                    #colour = "none",
                    size = "none") +
    ggplot2::labs(colour = "Degr\u00e9 de la\nnote m\u00e9diane:") +
    # ggplot2::scale_colour_discrete() +
    ggplot2::scale_colour_manual(
      values = c("#EB5646",  # Rouge vif
                 "#A3472A",  # Terre cuite foncee, plus rustique
                 "#A3478A",  # Terre cuite foncee, plus rustique
                 "black",  # Beige clair
                 "#FCF1DD",  # Beige clair
                 "#D9A066",  # Ocre dore, pour rechauffer et varier
                 "#7B2E2E")  # Bordeaux profond, pour l’ancrage visuel
    ) +
    # ggplot2::scale_colour_brewer(palette = 2) +
    # ggplot2::scale_color_viridis_d() +
    ggnetwork::theme_blank() +
    ggplot2::theme(
      panel.background = ggplot2::element_rect(fill='transparent'), #transparent panel bg
      plot.background = ggplot2::element_rect(fill='transparent', color=NA), #transparent plot bg
      panel.grid.major = ggplot2::element_blank(), #remove major gridlines
      panel.grid.minor = ggplot2::element_blank(), #remove minor gridlines
      legend.background = ggplot2::element_rect(fill='transparent'), #transparent legend bg
      legend.box.background = ggplot2::element_rect(fill='transparent') #transparent legend panel
    )
  return(pggnetwork)
}
```

```{r examples-plot_tvc_network, eval=FALSE}
triads <- read_sheet_triad()
playlist_id <- get_playlist_id(triad = "1 7")
songs <- tvc:::get_spotify_api_playlist(playlist_id = playlist_id, scope = "public")
data <- parse_triade(triads, songs)
print(plot_tvc_network(data))
```

```{r tests-plot_tvc_network}
test_that("plot_tvc_network works", {
  expect_true(inherits(plot_tvc_network, "function"))
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_plot_tvc_network.Rmd", vignette_name = "plot_tvc_network")
```

