---
title: "flat_write_missing_triade.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# write_missing_triade

```{r development-write_missing_triade}
# Prepare the code of your function here
```

```{r function-write_missing_triade}
#' Update Triad Google Sheet
#'
#' @param songs a tibble of songs from Spotify as returned by \code{\link{get_spotify_api_playlist}}
#' @param triads a tibble of triads from Google Sheet "Triade"
#' @param ss a google sheet identifier
#' @param triadeType a triad identifier, "1 7" for Vanessa Carlton triad
#'
#' @return \code{write_missing_triade} writes the missing songs in a google sheet "Missing Triade" so that the user can copy and paste them to the main "Triade" sheet
#' @export
#' @importFrom cli cli_alert_danger cli_alert_success
#' @importFrom dplyr filter select group_by summarise relocate anti_join join_by arrange distinct
#' @importFrom googlesheets4 write_sheet
#'
#' @examples
write_missing_triade <- function(songs, triads, ss = NULL, triadeType = "1 7") {
  if(is.null(triadeType)) {
    triadeType <- unique(songs$triad)
  }
  songsSpotify <- songs %>%
    dplyr::filter(triad %in% triadeType) %>% 
    dplyr::select(Song, Artist, ISRC, triad, Playlist_Order) %>%
    dplyr::group_by(Song, ISRC, triad) %>% 
    dplyr::summarise(Artist = paste(Artist, collapse = ", "),
                     Playlist_Order = head(Playlist_Order, 1L),
                     .groups = "drop") %>% 
    dplyr::relocate(Song, Artist, ISRC, triad)
  
  ## New triade missing from Google Sheet
  newTriade <- songsSpotify %>% 
    dplyr::anti_join(y = triads, by = dplyr::join_by(ISRC, triad)) %>% 
    dplyr::arrange(triad, Playlist_Order)
  
  ## Triads entries missing from Spotify playlist
  missingInSpotify <- dplyr::anti_join(
    x = dplyr::filter(triads, triad %in% triadeType),
    y = songsSpotify,
    by = dplyr::join_by(ISRC)
    ) %>% 
    dplyr::filter(!is.na(ISRC)) %>% 
    dplyr::distinct(Song, Artist, ISRC)
  
  if(nrow(missingInSpotify) > 0L) {
    cli::cli_alert_danger("Missing songs in Spotify playlist. Consider adding {paste('\\'', missingInSpotify$Song, '\\' - ', missingInSpotify$Artist, sep = '', collapse = '; ')}")
  }
  
  if(nrow(newTriade) > 0) {
    if(is.null(ss)) {
      keysAPI <- get_config(env = "google")
      ss <- keysAPI[["base_url"]]
    }
    googlesheets4::write_sheet(
      data = newTriade,
      sheet = "Missing Triade",
      ss = ss
    )
  } else {
    cli::cli_alert_success("The Triade Sheet is up to date.")
  }
}
```

```{r examples-write_missing_triade}
triads <- read_sheet_triad()
playlist_id <- get_playlist_id(triad = "1 7")
songs <- tvc:::get_spotify_api_playlist(playlist_id = playlist_id, scope = "public") %>% 
  dplyr::mutate(triad = "1 7")
write_missing_triade(songs = songs, triads = triads)
```

```{r tests-write_missing_triade}
test_that("write_missing_triade works", {
  expect_true(inherits(write_missing_triade, "function"))
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_write_missing_triade.Rmd", vignette_name = "Update Triade Google Sheet")
```

