# WARNING - Generated by {fusen} from dev/flat_bias_correction_triad.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("apply_time_space_weight works", {
  expect_true(inherits(apply_time_space_weight, "function")) 
})
