# WARNING - Generated by {fusen} from dev/flat_compute_population_estimates.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("estimate_population_by_country_year works", {
  expect_true(inherits(estimate_population_by_country_year, "function")) 
})
