# WARNING - Generated by {fusen} from dev/flat_bias_correction_triad.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("compute_triad_probability_old works", {
  expect_true(inherits(compute_triad_probability_old, "function")) 
})
