# WARNING - Generated by {fusen} from dev/flat_get_spotify_api_playlist.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("query_playlist works", {
  expect_true(inherits(query_playlist, "function")) 
})
