# WARNING - Generated by {fusen} from dev/flat_parse_triade.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("fix_album_date works", {
  expect_true(inherits(fix_album_date, "function")) 
  
  songs <- tibble::tibble(
    Album_Date = c(
      "2002-04-30", "1987", "2003-12-01", 
      "2000", "1987-11"
    ),
    item.album.release_date_precision = c(
      "day", "year", "day", "year", "month"
    ),
    Album_Year = c(
      2002, 1987, 1982, 1982, 1987
    )
  )
  testthat::expect_equal(
    fix_album_date(songs)[["Album_Date"]],
    expected = structure(
      c(11807, 6209, 12387, 10957, 6513),
      class = "Date"
    )
  )
  
})
