# WARNING - Generated by {fusen} from dev/flat_insert_line_breaks_adaptive.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("insert_line_breaks_adaptive works", {
  expect_true(inherits(insert_line_breaks_adaptive, "function"))
  texts <- c("Bluebird", "Blue Jeans", "Blue Velvet", "Blue Moon (Remaster)", "Blue Banisters")
  expect_equal(
    object = insert_line_breaks_adaptive(texts = texts, max_lines = 3L),
    expected = c("Bluebird", "Blue Jeans", "Blue Velvet",
                 "Blue Moon\n (Remaster)", "Blue Banisters")
    )
  
})
