# WARNING - Generated by {fusen} from dev/flat_bias_correction_triad.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("compute_interval_probability works", {
  expect_true(inherits(compute_interval_probability, "function")) 
  expect_lte(length(compute_interval_probability()), expected = 23L)
})
