# WARNING - Generated by {fusen} from dev/flat_triad_coverage.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("build_triad_from_config works", {
  expect_true(inherits(build_triad_from_config, "function")) 
})
