# WARNING - Generated by {fusen} from dev/flat_scale_palette_triad.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("tvc_corp_palette works", {
  expect_true(inherits(tvc_corp_palette, "function")) 
})
