# WARNING - Generated by {fusen} from dev/flat_get_spotify_api_playlist.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("auth_spotify works", {
  expect_true(inherits(auth_spotify, "function"))
  expect_no_error(token <- auth_spotify())
  expect_true(is.character(token))
  expect_gt(nchar(token), expected = 100L)
})
