# WARNING - Generated by {fusen} from dev/flat_bias_correction_triad.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("bias_correction_triad works", {
  expect_true(inherits(bias_correction_triad, "function"))
})
