# WARNING - Generated by {fusen} from dev/flat_triad_coverage.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("triad_coverage works", {
  expect_true(inherits(triad_coverage, "function"))
})
