# WARNING - Generated by {fusen} from dev/flat_plot_tvc_network.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("plot_tvc_network works", {
  expect_true(inherits(plot_tvc_network, "function"))
})
