# WARNING - Generated by {fusen} from dev/flat_scale_palette_triad.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("palette_gen_c works", {
  expect_true(inherits(palette_gen_c, "function")) 
})
