# WARNING - Generated by {fusen} from dev/flat_plot_tvc_histogram.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("plot_tvc_histogram works", {
  expect_true(inherits(plot_tvc_histogram, "function"))
})
