# WARNING - Generated by {fusen} from dev/flat_get_spotify_api_playlist.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("get_spotify_api_triad_playlists works", {
  expect_true(inherits(get_spotify_api_triad_playlists, "function")) 
})
