# WARNING - Generated by {fusen} from dev/flat_config.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("config works", {
  expect_true(inherits(get_config, "function"))
  expect_gte(length(get_config(env = "spotify")), expected = 4L)
})
