# WARNING - Generated by {fusen} from dev/flat_scale_palette_triad.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("scale_colour_tvc_d works", {
  expect_true(inherits(scale_colour_tvc_d, "function")) 
})
