# WARNING - Generated by {fusen} from dev/flat_write_missing_region.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("write_missing_region works", {
  expect_true(inherits(write_missing_region, "function"))
})
