# WARNING - Generated by {fusen} from dev/flat_config.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("get_playlist_id works", {
  expect_true(inherits(get_playlist_id, "function")) 
  expect_equal(object = get_playlist_id(name = "Vanessa Carlton"),
               expected = get_playlist_id(triad = "1 7"))
})
