# WARNING - Generated by {fusen} from dev/flat_parse_triade.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("clean_song_title works", {
  expect_true(inherits(clean_song_title, "function")) 
})
