# WARNING - Generated by {fusen} from dev/flat_plot_tvc_world.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("group_countries works", {
  expect_true(inherits(group_countries, "function"))
  expect_equal(
    object = {
      tibble::tibble(Region = c("Mexico", "Cuba", "Colombia", "France", "Belgium")) %>%
        tvc:::group_countries(Region) %>%
        dplyr::pull(Region_Group)
    },
    expected = c("Caribbean", "Caribbean", "Caribbean", "France", "France")
  )
})
