# WARNING - Generated by {fusen} from dev/flat_parse_triade.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("parse_triade works", {
  expect_true(inherits(parse_triade, "function"))
})
