# WARNING - Generated by {fusen} from dev/flat_compute_population_estimates.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("compute_population_estimates works", {
  expect_true(inherits(compute_population_estimates, "function"))
})
