# WARNING - Generated by {fusen} from dev/flat_get_spotify_api_playlist.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("get_spotify_api_playlist works", {
  expect_true(inherits(get_spotify_api_playlist, "function"))
  playlist_id <- get_playlist_id(triad = "1 7")
  expect_no_error(songs <- get_spotify_api_playlist(playlist_id = playlist_id, scope = "public"))
  expect_true(inherits(songs, "tbl"))
  expect_gt(nrow(songs), expected = 10L)
})
