# WARNING - Generated by {fusen} from dev/flat_read_sheet_triad.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("read_sheet_triad works", {
  expect_true(inherits(read_sheet_triad, "function"))
})
