# WARNING - Generated by {fusen} from dev/flat_bias_correction_triad.Rmd: do not edit by hand # nolint: line_length_linter.

#' Apply Triad Weight
#' 
#' Apply triad weight to songs. In case a song contains different triads, the maximum weight is kept.
#' @param songs a tibble of songs
#' @param w_triad 
#' @param regions 
#' @param group_year 
#'
#' @return \code{apply_triad_weight} returns a tibble
#' 
#' @noRd
#' @examples
#' # time_space_triad0 <- apply_triad_weight(
#' #   songs = songs,
#' #   w_triad = w_triad,
#' #   regions = regions
#' # )
apply_triad_weight <- function(songs, w_triad, regions, group_year = 1L) {
  time_space_triad0 <- songs %>% 
    ## Triad Weight
    dplyr::left_join(
      dplyr::select(w_triad, triad, weight_triad),
      by = dplyr::join_by(triad)
    ) %>%
    ## Years Group
    dplyr::mutate(Year_Group = floor(Album_Year / group_year) * group_year) %>% 
    ## Add Countries
    dplyr::inner_join(regions, by = dplyr::join_by(Artist)) %>%
    dplyr::mutate(Region = strsplit(Region, split = ", ")) %>%
    tidyr::unnest(Region) %>%
    ## Group Countries
    group_countries(Region) %>% 
    dplyr::group_by(ISRC, Region_Group, Year_Group) %>%
    dplyr::summarise(weight_triad = max(weight_triad),
                     .groups = "drop") %>% 
    ## Share a song between countries
    dplyr::group_by(ISRC, Year_Group) %>% 
    dplyr::mutate(weight_triad = weight_triad / dplyr::n(),
                  raw_triad = 1 / dplyr::n()) %>% 
    dplyr::ungroup() %>% 
    ## For a Year-Country, if all triad weights are very low, remove them
    dplyr::group_by(Year_Group, Region_Group) %>% 
    dplyr::mutate(
      all_low_triad_weights = all(weight_triad < 0.1),
      weight_triad = dplyr::if_else(all_low_triad_weights,
                                    raw_triad, 
                                    weight_triad)
    ) %>% 
    dplyr::select(-all_low_triad_weights) %>% 
    dplyr::ungroup()
  return(time_space_triad0)
}
