# WARNING - Generated by {fusen} from dev/flat_bias_correction_triad.Rmd: do not edit by hand # nolint: line_length_linter.

#' Apply Time & Space Weight
#' 
#' Apply a Time & Space group weight to individual songs.
#' @param w_triad2 
#' @param time_space_triad0 
#'
#' @return \code{apply_time_space_weight} returns a tibble with two columns ISRC and weighted_year_country
#' 
#' @noRd
#' @examples
#' apply_time_space_weight()
apply_time_space_weight <- function(w_triad2, time_space_triad0) {
  w_time_space <- w_triad2 %>% 
    ## Restrict a Year-Country group based on its expected proportion in the dataset
    dplyr::filter(weighted_prop_triad > 0) %>% 
    dplyr::mutate(weighted_year_country = dplyr::if_else(weighted_prop_triad > weight_year_country,
                                                         weight_year_country,
                                                         weighted_prop_triad) / weighted_prop_triad) %>%
    # dplyr::mutate(weighted_year_country = weighted_year_country / sum(weighted_year_country)) %>%
    dplyr::select(Region_Group, Year_Group, weighted_year_country)
  
  # time_space_triad0 %>% 
  #   dplyr::anti_join(w_time_space, by = dplyr::join_by(Region_Group, Year_Group)) %>% 
  #   dplyr::left_join(songs)
  
  w_time_space2 <- time_space_triad0 %>% 
    dplyr::left_join(w_time_space, by = dplyr::join_by(Region_Group, Year_Group)) %>% 
    ## Cancel Triad Weight
    dplyr::mutate(weighted_year_country = weighted_year_country * raw_triad / weight_triad) %>% 
    ## Aggregate Countries for Multi-Coutries Songs
    dplyr::group_by(ISRC) %>% 
    dplyr::summarise(weighted_year_country = mean(weighted_year_country)) %>% # sum
    ## Set Max Weight to 1 = 1 song
    dplyr::mutate(weighted_year_country = weighted_year_country / max(weighted_year_country, na.rm = TRUE))
  return(w_time_space2)
}
