# WARNING - Generated by {fusen} from dev/flat_get_spotify_api_playlist.Rmd: do not edit by hand # nolint: line_length_linter.

#' Authentifie l’accès Spotify
#' @param client_id Optionnel (sinon lu depuis SPOTIFY_CLIENT_ID)
#' @param client_secret Optionnel (sinon lu depuis SPOTIFY_CLIENT_SECRET)
#' @return \code{auth_spotify} returns a token (invisible) used by spotifyr
#' @importFrom spotifyr get_spotify_access_token
#' @noRd
#' @examples
#' token <- tvc:::auth_spotify()
auth_spotify <- function(client_id = NULL,
                         client_secret = NULL, scope = c("public")) {
  if(is.null(client_id)) {
    keysAPI <- get_config(env = "spotify")
  } else {
    keysAPI <- list("client_id" = client_id,
                    "client_secret" = client_secret)
  }
  
  stopifnot(nzchar(keysAPI$client_id), nzchar(keysAPI$client_secret))
  
  if(!("private" %in% scope)) {
    ## public playlists only
    token <- spotifyr::get_spotify_access_token(client_id = keysAPI$client_id,
                                                client_secret = keysAPI$client_secret)
  } else {
    ## we need the scope playlist-read-private
    ## Spotify interdit l'url utilise par spotifyr
    tvc_get_spotify_authorization_code <- function (client_id = Sys.getenv("SPOTIFY_CLIENT_ID"),
                                                    client_secret = Sys.getenv("SPOTIFY_CLIENT_SECRET"),
                                                    scope = spotifyr::scopes()) {
      endpoint <- httr::oauth_endpoint(authorize = "https://accounts.spotify.com/authorize", 
                                       access = "https://accounts.spotify.com/api/token")
      app <- httr::oauth_app(appname = "get-tvc",
                             key = client_id,
                             secret = client_secret,
                             redirect_uri = "http://127.0.0.1:1410/")
      # app <- httr::oauth_app(appname = "spotifyr",
      #                        key = client_id,
      #                        secret = client_secret,
      #                        redirect_uri = "http://127.0.0.1:1410/")
      token <- (purrr::safely(.f = httr::oauth2.0_token))(endpoint = endpoint, 
                                                          app = app, scope = scope)
      if (!is.null(token$error)) {
        token$error
      }
      else {
        token$result
      }
    }
  
    token <- tvc_get_spotify_authorization_code(
      client_id = keysAPI$client_id,
      client_secret = keysAPI$client_secret,
      scope = "playlist-read-private"
      )
    token <- token$credentials$access_token
  }
  invisible(token)
}
