# WARNING - Generated by {fusen} from dev/flat_bias_correction_triad.Rmd: do not edit by hand # nolint: line_length_linter.

#' Bias Correction Triad
#'
#' @param songs a tibble of songs.
#'
#' @return \code{bias_correction_triad} returns a tibble, with time and space weights for each song, taking into account triad weight.
#' @export
#'
#' @examples
#' w_time_space2 <- bias_correction_triad(songs, regions, group_year = 1L)
bias_correction_triad <- function(songs, regions, group_year = 1L, verbose = TRUE) {
  stat_interval <- compute_interval_probability(prob_alien = 0.15)
  
  interval_occurence <- compute_triad_probability(stat_interval)
  
  ## triad occurence within a song based on the probability of having n distinct triads within a song
  triad_occurence <- mutate_triad_occurence_per_song(
    interval_occurence = interval_occurence,
    songs = songs,
    nb_fake_song = 5e4L
  )
  
  w_triad <- compute_triad_weight(
    songs = songs,
    triad_occurence = triad_occurence
  )
  
  population <- compute_population_estimates(update = FALSE, group_year = group_year)
  
  time_space_triad0 <- apply_triad_weight(
    songs = songs,
    w_triad = w_triad,
    regions = regions,
    group_year = group_year
  )
  
  w_triad2 <-compute_time_space_weight(
    time_space_triad0 = time_space_triad0,
    population = population
  )
  
  if(verbose) {
    ## Biggest non-representated Year-Country groups
    message("Biggest non-representated Year-Country groups:")
    w_triad2 %>% 
      dplyr::filter(weighted_prop_triad == 0) %>% 
      dplyr::filter(Year_Group > 1940) %>% 
      dplyr::arrange(dplyr::desc(weight_year_country)) %>% 
      dplyr::slice_head(n = 10L) %>% 
      dplyr::select(Region_Group, Year_Group, weight_year_country) %>% 
      as.data.frame() %>% 
      print()
  }
  
  w_time_space2 <- apply_time_space_weight(
    w_triad2 = w_triad2,
    time_space_triad0 = time_space_triad0
  )
  
  if(rlang::has_name(x = songs, name = "weighted_year_country")) {
    ## Remove pre-existing column weighted_year_country
    songs <- songs %>% 
      dplyr::select(-weighted_year_country)
  }
  
  ## Most representative and least representative songs
  if(verbose) {
    message("Most representative and least representative songs")
    w_time_space2 %>% 
      dplyr::arrange(dplyr::desc(weighted_year_country)) %>% 
      dplyr::left_join(songs, by = dplyr::join_by(ISRC)) %>% 
      dplyr::filter(
        !dplyr::between(weighted_year_country,
                        left = quantile(weighted_year_country, na.rm = TRUE, probs = .01),
                        right = quantile(weighted_year_country, na.rm = TRUE, probs = .99))
      ) %>%
      dplyr::select(ISRC, Song, Artist, Album_Year, triad, weighted_year_country) %>% 
      dplyr::distinct(ISRC, Song, Album_Year, triad, weighted_year_country, .keep_all = TRUE) %>% 
      dplyr::select(-ISRC) %>% 
      print()
  }
  
  songs <- songs %>% 
    dplyr::left_join(w_time_space2, by = dplyr::join_by(ISRC)) %>%
    dplyr::mutate(
      weighted_year_country = dplyr::if_else(is.na(weighted_year_country),
                                             1,
                                             weighted_year_country)
    )
  return(songs)
}
