# WARNING - Generated by {fusen} from dev/flat_triad_coverage.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get Triad Type Table
#' 
#' Read config file and list all triads#' 
#' @param env a character string
#'
#' @return \code{build_triad_from_config} returns a triad table.
#' 
#' @export
#' @examples
#' tabTriads <- build_triad_from_config(env = "spotify")
build_triad_from_config <- function(env = "spotify"){
  tabTriads <- get_config(env = env)$playlists %>%
    purrr::transpose() %>%
    tibble::as_tibble() %>%
    tidyr::unnest(cols = c(triad, name, playlist))
  
  if(any(duplicated(tabTriads[["playlist"]]))) {
    cli::cli_abort(message = "Duplicated playlist_id : {tabTriads[['playlist']][duplicated(tabTriads[['playlist']])]}")
  }
  
  return(tabTriads)
}
