# WARNING - Generated by {fusen} from dev/flat_parse_triade.Rmd: do not edit by hand # nolint: line_length_linter.

#' Clean Song Names
#' 
#' Remove "Remaster version" and "featuring..." mentions.
#' 
#' @param .data a data frame with two columns Song and Artist
#'
#' @return \code{clean_song_title} returns a tibble with a modified column Song
#' 
#' @export
#' @examples
#' tibble::tibble(Song = c("You're So Sweet Darling, BWV 565: I. Toccata", "That's All Right - Remaster 2006 definitive edition"),
#'                Artist = c("Belzebuth & The Jeremies", "Benny Goodman")) %>% 
#'   clean_song_title()
clean_song_title <- function(.data){
  .data <- .data %>% 
    ## Nettoyer les noms de chansons
    dplyr::mutate(Song = gsub(" - .*Remaster.*$", "", Song),
                  Song = gsub("\\(feat.*\\)$", "", Song),
                  Song = gsub("\\(from.*\\)$", "", Song),
                  Song = gsub("Concerto for Trumpet and Orchestra in A-Flat Major",
                              "Concerto for Trumpet (Arutiunian)",
                              Song,
                              fixed = TRUE),
                  Song = gsub(" (with Chaka Khan)", "", Song, fixed = TRUE),
                  Song = gsub(" - From  Over The Top  Soundtrack", "", Song, fixed = TRUE),
                  Song = gsub("Bach, JS: Orchestral Suite No. 2 in B Minor, BWV 1067: VII. ", "", Song, fixed = TRUE),
                  Song = gsub("(British National Anthem 1952-2022)", "", Song, fixed = TRUE),
                  Song = gsub("/Soundtrack Version", "", Song, fixed = TRUE),
                  Song = gsub("- Jeremy Wheatley Mix", "", Song, fixed = TRUE),
                  Song = gsub("- Unedited Single Version; 2006 Remaster", "", Song, fixed = TRUE),
                  Song = gsub(", BWV 565: I. Toccata", "", Song, fixed = TRUE),
                  Song = gsub("(2024 Remaster)", "", Song, fixed = TRUE),
                  Song = dplyr::if_else(Artist == "Le Youth" & Song == "Underwater",
                                        paste(Song, "(LY)"), Song),
                  Song = gsub(" \\)", "\\)", Song))
  return(.data)
}
