# WARNING - Generated by {fusen} from dev/flat_compute_population_estimates.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compute population Estimates
#' 
#' Population estimates per year and per country.
#' @param update a boolean
#' @param group_year an integer giving the number of year for grouping.
#'
#' @return \code{compute_population_estimates} returns a tibble of worldwide population estimates
#' @export
#' @importFrom dplyr select mutate filter case_when rename
#' @importFrom janitor clean_names
#' @importFrom purrr map
#' @importFrom readr parse_number read_csv
#' @importFrom rvest read_html html_elements html_table
#' @importFrom stringr str_remove
#' @importFrom tibble tibble
#' @importFrom tidyr unnest
#'
#' @examples
#' population <- compute_population_estimates(update = FALSE)
#' # population %>%
#' #   ggplot2::ggplot() +
#' #   ggplot2::aes(Year_Group, weight_year_country, group = country) +
#' #   ggplot2::geom_line()
compute_population_estimates <- function(update = TRUE, group_year = 1L) {
  if(update) {
    url <- "https://worldostats.com/country-stats/world-population-by-country/"

    # Scraping des deux tableaux sur la même page
    tables <- rvest::read_html(url) %>%
      rvest::html_elements("table") %>%
      purrr::map(~ rvest::html_table(.x, fill = TRUE))

    raw_countries <- tables[[1]]
    raw_years     <- tables[[2]]

    # Nettoyage
    countries <- raw_countries %>%
      janitor::clean_names() %>%
      dplyr::select(
        country, x2025_population, percent_change
      ) %>%
      dplyr::mutate(
        percent_change = readr::parse_number(stringr::str_remove(percent_change, "%")) / 100,
        x2025_population = readr::parse_number(x2025_population)
      )
    
    years <- raw_years %>%
      janitor::clean_names() %>%
      dplyr::mutate(
        world_population = readr::parse_number(world_population)
      ) %>%
      dplyr::filter(year > 1600)

    saveRDS(object = countries, file = "countries.RDS")
    saveRDS(object = years, file = "years.RDS")
  } else {
    countries <- readRDS(file = "countries.RDS")
    years     <- readRDS(file = "years.RDS")
  }

  clean_countries <- tibble::tibble(
    file = list.files(path = system.file(package = "tvc", "extdata"),
                      full.names = TRUE)
  ) %>%
    ## Csv files from https://www.macrotrends.net/datasets/global-metrics/countries/
    dplyr::mutate(country = dplyr::case_when(
      grepl("China", file) ~ "China",
      grepl("France", file) ~ "France",
      grepl("India", file) ~ "India",
      grepl("United-States", file) ~ "USA",
      grepl("United-Kingdom", file) ~ "UK",
      grepl("Japan", file) ~ "Japan",
      grepl("Germany", file) ~ "Germany",
      grepl("Australia", file) ~ "Australia",
      grepl("Brazil", file) ~ "Brazil",
      grepl("Russia", file) ~ "Russia",
      grepl("Sweden", file) ~ "Sweden",
      grepl("Mexico", file) ~ "Mexico",
      grepl("Taiwan", file) ~ "Taiwan",
      TRUE ~ file
    )) %>%
    dplyr::mutate(data = purrr::map(file, ~ suppressMessages(readr::read_csv(.x, show_col_types = FALSE)))) %>%
    tidyr::unnest(data) %>%
    dplyr::rename(year = `...1`) %>%
    dplyr::select(-file) %>%
    dplyr::mutate(Accurate = TRUE)
  
  # Estimation
  estimates <- estimate_population_by_country_year(
    countries_df = countries,
    years_df = years,
    clean_countries = clean_countries,
    group_year = group_year
  )
  return(estimates)
}
