# WARNING - Generated by {fusen} from dev/flat_bias_correction_triad.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compute Time & Space Weight
#' 
#' Description
#' 
#' @param time_space_triad0 a tibble with triad weight for each song-country-year.
#' @param population a tibble population per year and country
#'
#' @return \code{compute_time_space_weight} returns a tibble \code{w_triad2}
#' 
#' @noRd
#' @examples
#' compute_time_space_weight()
compute_time_space_weight <- function(time_space_triad0, population) {
  time_space_triad <- time_space_triad0 %>% 
    dplyr::group_by(Region_Group, Year_Group) %>% 
    dplyr::summarise(weighted_triad = sum(weight_triad),
                     raw_triad = sum(raw_triad),
                     .groups = "drop") %>% 
    dplyr::mutate(weighted_prop_triad = weighted_triad / sum(weighted_triad),
                  raw_prop_triad = raw_triad / sum(raw_triad))
  
  w_triad2 <- population %>%
    dplyr::left_join(time_space_triad,
                     by = dplyr::join_by(Year_Group,
                                         Region_Group)) %>%
    # dplyr::filter(!is.na(weighted_prop_triad)) %>%
    dplyr::mutate(
      dplyr::across(.cols = c(weighted_triad, raw_triad,
                              weighted_prop_triad, raw_prop_triad),
                    .fns = ~ dplyr::if_else(is.na(.), 0, .))) %>% 
    ## Renormalisation
    dplyr::mutate(weight_year_country = weight_year_country / sum(weight_year_country),
                  weighted_prop_triad = weighted_prop_triad / sum(weighted_prop_triad),
                  raw_prop_triad = raw_prop_triad / sum(raw_prop_triad)) %>% 
    dplyr::select(-c(estimated_population, Accurate))
  return(w_triad2)
}
