# WARNING - Generated by {fusen} from dev/flat_bias_correction_triad.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compute Triad Probability
#' 
#' Description
#' @param stat_interval a named numeric vector as returned by \code{compute_interval_probability}
#'
#' @return \code{compute_triad_probability} returns a tibble of theoretical triad probabilities
#' 
#' @noRd
#' @examples
#' stat_interval <- compute_interval_probability(nb_interval = 3)
#' interval_occurence <- compute_triad_probability(stat_interval)
compute_triad_probability <- function(stat_interval){
  interval_occurence0 <- tibble::tibble(
    interval = as.integer(names(stat_interval)),
    frequency = as.numeric(stat_interval)
  ) %>% 
    dplyr::cross_join(x = ., y = ., suffix = c("_first", "_second")) %>% 
    dplyr::mutate(frequency = frequency_first * frequency_second) %>% 
    ## Introducing Negative Intervals
    dplyr::mutate(dplyr::across(dplyr::contains("interval"),
                                .fns = ~ purrr::map(.x = ., .f = ~ .x * c(1, -1)))) %>% 
    tidyr::unnest(cols = interval_first) %>% 
    tidyr::unnest(cols = interval_second)
  
  interval_cum_occurence <- interval_occurence0 %>% 
    dplyr::mutate(interval_cum = interval_first + interval_second) %>% 
    dplyr::group_by(interval_cum) %>% 
    dplyr::summarise(frequency = sum(frequency)) %>% 
    dplyr::mutate(frequency = frequency / max(frequency))
    # plot(interval_cum_occurence)
  
  interval_occurence <- interval_occurence0 %>% 
    dplyr::select(-c(frequency_first, frequency_second)) %>% 
    ## Range octave
    dplyr::filter(
      abs(interval_first) < 12,
      abs(interval_second) < 12
    ) %>% 
    ## Take into account the interval between 1st and 3rd note
    dplyr::mutate(interval_cum = interval_first + interval_second) %>% 
    dplyr::filter(
      abs(interval_cum) < 12
    ) %>%
    dplyr::left_join(
      y = interval_cum_occurence,
      by = dplyr::join_by(interval_cum),
      suffix = c("", "_cum")
    ) %>%
    dplyr::mutate(frequency = frequency * frequency_cum) %>%
    dplyr::select(-frequency_cum) %>%
    ## Name triads
    dplyr::mutate(triad = paste(interval_first, interval_second))
  return(interval_occurence)
}
