# WARNING - Generated by {fusen} from dev/flat_bias_correction_triad.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compute Interval Probability
#' 
#' Generate Interval Probability
#' 
#' @param nb_interval 
#' @param prob_alien 
#'
#' @return \code{compute_interval_probability} returns a numeric vector of probabilities
#' 
#' @noRd
#' @examples
#' stat_interval <- compute_interval_probability()
compute_interval_probability <- function(nb_interval = 10000L, prob_alien = 0.15){
  major_scale <- c(prob_alien, 1, prob_alien, 1, 1, prob_alien, 1, prob_alien, 1, prob_alien, 1, 1)
  minor_scale <- c(prob_alien, 1, 1, prob_alien, 1, prob_alien, 1, 1, prob_alien, prob_alien, 1, 1)
  x <- list(rep(major_scale, 4L),
            rep(minor_scale, 4L))
  weight_scale <- c(1, .3)
  scale <- sample(x = x, size = nb_interval, replace = TRUE, prob = weight_scale)
  note_start <- purrr::map_dbl(
    .x = scale,
    .f = ~ sample(x = 1L:length(major_scale),
                  size = 1L, replace = TRUE,
                  prob = head(.x, length(major_scale)))
  )
  scope_interval <- seq_len(length(major_scale) * 2L - 1L) # notes from scale
  raw_weight_interval <- sort(scope_interval, decreasing = TRUE)/max(scope_interval)
  raw_weight_interval2 <- raw_weight_interval # exp(x = -0.3 *  (scope_interval - 1))
  start_note_exp_descr <- 7L # if(x < 7) {-x} else {- x^2}
  raw_weight_interval[start_note_exp_descr:length(raw_weight_interval)] <- raw_weight_interval[start_note_exp_descr:length(raw_weight_interval)] * raw_weight_interval2[1L:(length(raw_weight_interval) + 1L - start_note_exp_descr)]
  # plot(raw_weight_interval)
  number_notes <- purrr::pmap_dbl(
    .l = list(scale,
              note_start),
    .f = ~ sample(x = scope_interval -1L, size = 1L, replace = TRUE,
                  prob = raw_weight_interval * ..1[(..2 + 1L):(..2 + length(scope_interval) - 0L)])
  )
  intervals <- purrr::pmap_dbl(.l = list(note_start,
                                         number_notes,
                                         scale),
                               .f = ~ sum(rep(1, length(..3))[..1:(..1 + ..2)]))
  stat_interval <- table(intervals) / max(table(intervals))
  
  ## Old (only regular scales)
  # major_scale <- c(2L, 2L, 1L, 2L, 2L, 2L, 1L)
  # minor_scale <- c(2L, 1L, 2L, 2L, 1L, 3L, 1L)
  # nb_interval <- 10000L
  # x <- list(rep(major_scale, 4L),
  #           rep(minor_scale, 4L))
  # weight_scale <- c(1, .3)
  # scale <- sample(x = x, size = nb_interval, replace = TRUE, prob = weight_scale)
  # note_start <- sample(x = 1L:length(major_scale), size = nb_interval, replace = TRUE)
  # scope_interval <- seq_len(length(major_scale) * 2L - 1L) # notes from scale
  # weight_interval <- sort(scope_interval, decreasing = TRUE)/max(scope_interval) # exp(x = -0.3 *  (scope_interval - 1))
  # number_notes <- sample(x = scope_interval -1L, size = nb_interval, replace = TRUE, prob = weight_interval)
  # intervals <- purrr::pmap_dbl(.l = list(note_start,
  #                                        number_notes,
  #                                        scale),
  #                              .f = ~ sum(..3[..1:(..1 + ..2)]))
  # stat_interval <- table(intervals) / max(table(intervals))
  # plot(stat_interval)
  return(stat_interval)
}
