# WARNING - Generated by {fusen} from dev/flat_compute_population_estimates.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @return \code{estimate_population_by_country_year} returns population estimates per year and country.
#' 
#' @noRd
#' @importFrom dplyr mutate case_match rows_upsert rename group_by if_else ungroup select contains summarise_all
#' @importFrom tibble tibble
#' @importFrom tidyr expand_grid
#' @examples
#' estimate_population_by_country_year()
estimate_population_by_country_year <- function(countries_df, years_df, clean_countries, group_year = 1) {
  years_df_interpolated <- tibble::tibble(
    year = min(years_df[["year"]]):max(years_df[["year"]]),
    world_population = approx(x = years_df[["year"]],
                              y = years_df[["world_population"]], xout = year)$y
  )
  countries_df %>%
    dplyr::mutate(
      country = dplyr::case_match(country,
                                  "United States" ~ "USA",
                                  "United Kingdom" ~ "UK",
                                  .default = country)
    ) %>%
    dplyr::mutate(x2025_world_population = sum(x2025_population)) %>%
    tidyr::expand_grid(years_df_interpolated) %>%
    dplyr::mutate(
      estimated_population = world_population * x2025_population / x2025_world_population,
    ) %>%
    dplyr::mutate(Accurate = FALSE) %>%
    dplyr::rows_upsert(dplyr::rename(clean_countries,
                                     estimated_population = Population),
                       by = c("country", "year")) %>%
    ## Correction on inaccurate data
    dplyr::group_by(year) %>%
    dplyr::mutate(
      estimated_population = dplyr::if_else(
        Accurate,
        estimated_population,
        false = estimated_population * (world_population - sum(estimated_population * Accurate)) / sum(estimated_population * !Accurate)
      )
    ) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(
      weight_year_country = estimated_population / sum(estimated_population) # max(world_population)
    ) %>%
    dplyr::select(-c(dplyr::contains("2025"), world_population, percent_change)) %>%
    ## Year Group
    dplyr::mutate(Year_Group = floor(year / group_year) * group_year) %>%
    dplyr::select(-year) %>%
    ## Group Countries
    group_countries(country) %>%
    dplyr::select(-country) %>%
    ## Sum over Year and Countries
    dplyr::group_by(Region_Group, Year_Group) %>%
    dplyr::summarise_all(.funs = sum) %>%
    dplyr::ungroup()
}
