# WARNING - Generated by {fusen} from dev/flat_parse_triade.Rmd: do not edit by hand # nolint: line_length_linter.

#' Fix Album Dates
#' 
#' Album release dates are provided as strings of different precisions : year, month, day.
#' 
#' @param songs a tibble of songs as returned by Spotify.
#'
#' @return \code{fix_album_date} returns a tibble with a column Album_Date as Date.
#' 
#' @noRd
#' @examples
#' songs <- tibble::tibble(
#'   Album_Date = c(
#'     "2002-04-30", "1987", "2003-12-01", 
#'     "2000", "1987-11"
#'   ),
#'   item.album.release_date_precision = c(
#'     "day", "year", "day", "year", "month"
#'   ),
#'   Album_Year = c(
#'     2002, 1987, 1982, 1982, 1987
#'   )
#' )
#' fix_album_date(songs)
fix_album_date <- function(songs){
  # songs <- readRDS("songs.RDS") |> 
  #   dplyr::distinct(Album_Date, item.album.release_date_precision, Album_Year)
  songs |>
    dplyr::mutate(
      Album_Date2 = dplyr::case_when(
        item.album.release_date_precision == "day" ~ Album_Date,
        item.album.release_date_precision == "month" ~ paste0(Album_Date, "-01"),
        item.album.release_date_precision == "year" ~ paste0(Album_Date, "-01-01")
      ),
      Album_Date2 = as.Date(Album_Date2)
    ) |> 
    # dplyr::filter(lubridate::year(Album_Date2) != Album_Year)
    dplyr::mutate(
      Album_Date2 = dplyr::case_when(
        lubridate::year(Album_Date2) != Album_Year ~ as.Date(paste0(Album_Year, "-01-01")),
        TRUE ~ Album_Date2
      )
    ) |> 
    dplyr::mutate(Album_Date = Album_Date2) |> 
    dplyr::select(-Album_Date2)
}
