# WARNING - Generated by {fusen} from dev/flat_config.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get Credentials for database common Data Hub
#'
#' Internal function used in \code{\link{con_cdh_api_edit}} and \code{\link{con_cdh_api_read}}
#' @param env database name according to the config.yml file. Either "bruits_noprod" or "bruits_prod".
#' @param template a boolean specifying if \code{get_config}
#' should look for a config.yml file or a default config-template.yml file.
#'
#' @return a list with credentials that allows to access a database
#' @importFrom attempt stop_if_not warn_if stop_if
#' @importFrom config get
#' @importFrom glue glue
#' @examples
#' \dontrun{
#' keysAPI <- get_config("spotify")
#' }
#' keysAPI <- tvc:::get_config("spotify")
#' @noRd
# Suggested : @importFrom config get
get_config <- function(env = "spotify", template = FALSE) {
  if (template) {
    file <- "config-template.yml"
  } else {
    file <- "config.yml"
  }
  configFiles <- c(
    file,
    file.path("./inst", file),
    system.file(file, package = "xAcou"),
    file.path("../inst", file), # for vignettes
    file.path("../../inst", file), # for tests
    ## for tests inside RMD Check and test coverage
    file.path(
      "D:", "02-Pr_MUSIQUE",
      "tvc", "inst", file
    )
  )
  configFilesExist <- file.exists(configFiles)
  attempt::stop_if_not(any(configFilesExist),
    msg = "No config.yml found. Use `set_cdh_config()`"
  )
  ## Test available config files, one after another
  ## until keys are not NULL
  keysAPI <- NULL
  i <- 0
  configFiles <- configFiles[configFilesExist]
  while (is.null(keysAPI) & i < length(configFiles)) {
    i <- i + 1L
    configFile <- configFiles[i]
    keysAPI <- config::get(value = env, file = configFile)
    attempt::warn_if(is.null(keysAPI),
      msg = glue::glue("no entry {env} found in {configFile}")
    )
    ## Test config format
    attempt::stop_if(!is.null(keysAPI) && is.null(keysAPI[["client_secret"]]),
      msg = glue::glue(
        configFile, " is outdated. ",
        "Use `set_cdh_config(keysProd = 'xxx', keysPreProd = 'yyy')`"
      )
    )
  }
  return(keysAPI)
}

