# WARNING - Generated by {fusen} from dev/flat_get_spotify_api_playlist.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get All Triads
#' 
#' A Wrapper around \code{\link{get_spotify_api_playlist}} to get all triad's songs at once in an optimized way
#' 
#' @return \code{get_spotify_api_triad_playlists} returns a tibble of songs for different triads
#' 
#' @export
#' @examples
#' # get_spotify_api_triad_playlists()
get_spotify_api_triad_playlists <- function(){
  ## Exemple Reading private playlist
  # songsNegTVC <- tvc:::get_spotify_api_playlist(playlist_id = "1wAEEcvkLBETRvIs06BK1E", scope = "private")
  tabTriads <- get_config(env = "spotify")$playlists %>%
    purrr::transpose() %>%
    tibble::as_tibble() %>%
    tidyr::unnest(cols = c(triad, name, playlist))
  
  songs <- tabTriads %>%
    # Filter out non-triad
    dplyr::filter(grepl(pattern = "^-?[0-9]+ -?[0-9]+$", x = triad)) %>%
    dplyr::mutate(songs = get_spotify_api_playlist(playlist_id = playlist, scope = "private"))
  
  songs <- songs %>%
    tidyr::unnest(cols = songs)
  
  return(songs)
}
