# WARNING - Generated by {fusen} from dev/flat_config.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get Playlist id
#' 
#' Get the spotify playlist id based on the name of the triad
#' 
#' @param triad a character string (exemple : "1 7")
#' @param name a character string, it can be partial (exemple : "Carlton"). 
#'
#' @return \code{get_playlist_id} returns a Spotify playlist id
#' 
#' @export
#' @examples
#' get_playlist_id(triad = "1 7")
#' get_playlist_id(name = "Vanessa Carlton")
get_playlist_id <- function(triad = NULL, name = NULL){
  keysAPI <- get_config(env = "spotify")
  tabTriads <- keysAPI[["playlists"]] %>%
    purrr::transpose() %>%
    tibble::as_tibble() %>%
    tidyr::unnest(cols = c(triad, name, playlist)) %>% 
    dplyr::rename(triad_identifier = triad,
                  triad_name = name)
  if(!is.null(triad)) {
    out <- tabTriads %>% 
      dplyr::filter(triad_identifier == triad) %>% 
      dplyr::pull(playlist)
  } else {
    if(!is.null(name)) {
      out <- tabTriads %>% 
        dplyr::filter(grepl(name, x = triad_name)) %>%
        dplyr::arrange(nchar(triad_name)) %>% 
        dplyr::slice_head(n = 1L) %>% 
        dplyr::pull(playlist)
    }
  }
  return(out)
}
