# WARNING - Generated by {fusen} from dev/flat_plot_tvc_world.Rmd: do not edit by hand # nolint: line_length_linter.

#' Group Countries
#' 
#' This function aims at grouping countries that share artists music. For exemple, belgium singer Angèle is very popular in France so it makes sense to gather those two countries.
#' 
#' @return \code{group_countries} returns a tibble with an extra row \code{Region_Group}
#' 
#' @noRd
#' @examples
#' tibble::tibble(Region = c("Mexico", "Cuba", "Colombia", "France", "Belgium")) %>%
#'   tvc:::group_countries(Region)
group_countries <- function(.data, col_name) {
  col_name <- rlang::enquo(col_name)
  dplyr::mutate(
    .data = .data,
    Region_Group = dplyr::case_match(
      !!col_name,
      c("China", "Taiwan", "Singapore") ~ "China",
      c("France", "Belgium") ~ "France",
      c("Mexico", "Colombia", "Puerto Rico", "Cuba", "Panama", "Costa Rica") ~ "Caribbean",
      c("Ireland", "UK") ~ "UK",
      c("Australia", "New Zealand") ~ "Australia",
      c("Sweden", "Norway", "Finland") ~ "Scandinavia",
      .default = !!col_name
    )
  )
}
