# WARNING - Generated by {fusen} from dev/flat_bias_correction_triad.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compute Triad Probability (within a song)
#' 
#' Triad occurence within a song based on the probability of having n distinct triads within a song.
#' 
#' @param interval_occurence a tibble as returned by \code{compute_triad_probability}
#' @param songs a tibble of songs with at least a column `ISRC` and `triad`.
#' @param nb_fake_song 
#'
#' @return \code{mutate_triad_occurence_per_song} returns a tibble triad_occurence
#' 
#' @noRd
#' @examples
#' stat_interval <- compute_interval_probability(nb_interval = 3)
#' interval_occurence <- compute_triad_probability(stat_interval)
#' songs <- tibble::tibble(
#'   ISRC = sample(LETTERS, size = 15L),
#'   triad = sample(x = unique(interval_occurence[["triad"]]),
#'                  size = 15L, replace = TRUE)
#' )
#' triad_occurence <- mutate_triad_occurence_per_song(
#'   interval_occurence = interval_occurence,
#'   songs = songs,
#'   nb_fake_song = 5L
#' )
mutate_triad_occurence_per_song <- function(interval_occurence, songs, nb_fake_song = 5e4L) {
  nb_distinct_triad <- songs %>% 
    dplyr::group_by(ISRC) %>% 
    dplyr::summarise(Nb_triad = length(unique(triad))) %>% 
    dplyr::count(Nb_triad) %>% 
    # dplyr::filter(Nb_triad > 5) %>%
    dplyr::mutate(weight = n / sum(n))
  
  known_distinct_triads <- interval_occurence %>% 
    dplyr::filter(triad %in% songs[["triad"]])
  
  fake_nb_triad <- sample(
    x = nb_distinct_triad[["Nb_triad"]],
    size = nb_fake_song, replace = TRUE,
    prob = nb_distinct_triad[["weight"]]
  )
  fake_songs <- purrr::map(
    .x = fake_nb_triad,
    .f = ~ sample(
      x = known_distinct_triads[["triad"]],
      size = .x, replace = FALSE,
      prob = known_distinct_triads[["frequency"]]
    )
  )
  
  triad_occurence <- known_distinct_triads %>% 
    dplyr::mutate(
      frequency_song = purrr::map_dbl(
        .x = triad,
        .f = ~ sum(purrr::map_lgl(
          .x = fake_songs,
          .f = function(x) {.x %in% x}
        ))
      )
    ) %>% 
    dplyr::group_by(frequency) %>% 
    dplyr::mutate(frequency_song = mean(frequency_song)) %>% 
    dplyr::ungroup() %>% 
    dplyr::mutate(frequency_song = frequency_song * sum(frequency) / sum(frequency_song))
  
  # triad_occurence %>% 
  #   ggplot2::ggplot() +
  #   ggplot2::aes(frequency, frequency_song) +
  #   ggplot2::geom_abline(slope = 1, intercept = 0) +
  #   ggplot2::geom_point() +
  #   ggplot2::theme_bw()
  
  triad_occurence <- triad_occurence %>% 
    dplyr::mutate(frequency = frequency_song) %>% 
    dplyr::select(-frequency_song)
  return(triad_occurence)
}
