# WARNING - Generated by {fusen} from dev/flat_scale_palette_triad.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @return a palette continuous
#' 
#' @noRd
#' @examples
#' tvc:::palette_gen_c()
palette_gen_c <- function(palette = "gradient", direction = 1, ...) {

  pal <- tvc_corp_palette(palette)

  pal <- if (direction >= 0) pal else rev(pal)

  grDevices::colorRampPalette(pal, ...)

}
