# WARNING - Generated by {fusen} from dev/flat_scale_palette_triad.Rmd: do not edit by hand # nolint: line_length_linter.

#' Discrete Colour palette generation
#' 
#' Description
#' @param palette either gradient or "main" or ?
#' @param direction 1 for onward or -1 for downward
#' @param ... other params ?
#' 
#' @return \code{palette_gen_d} returns a discrete colour palette
#' 
#' @noRd
#' @examples
#' tvc:::palette_gen_d()
palette_gen_d <- function(palette = "main", direction = 1) {

  function(n) {

    if (n > length(tvc_corp_palette(palette))) {
      warning("Not enough colors in this palette!")
    } else {

      all_colors <- tvc_corp_palette(palette)

      all_colors <- unname(unlist(all_colors))
      
      all_colors <- head(all_colors, n = n)

      all_colors <- if (direction >= 0) all_colors else rev(all_colors)

      color_list <- all_colors[1:n]

    }
  }
}
