# WARNING - Generated by {fusen} from dev/flat_triad_coverage.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Triad Coverage
#'
#' @param triads a tibble triad
#' @param weighted a boolean specifying if songs should be weighted using tvc's bias correction method
#'
#' @return \code{plot_triad_coverage} plots a triad coverage heatmap
#' 
#' @export
#' @examples
#' triads <- read_sheet_triad()
#' plot_triad_coverage(triads = triads)
plot_triad_coverage <- function(triads, weighted = TRUE){
  dat <- triad_coverage(triads = triads, weighted = weighted) 
  dat %>%
    ggplot2::ggplot() +
    ggplot2::aes(x = First_Interval, y = Second_Interval,
                 fill = Weighted_Nb_Songs,
                 colour = triad %in% c("1 7", "-1 8", "-1 -7")) +
    ggplot2::geom_raster() +
    ggplot2::geom_text(ggplot2::aes(label = sub("Triade ", "Triade\n", name)),
                       colour = dplyr::if_else(dat$Weighted_Nb_Songs < 160L, "black", "white")) +
    # ggplot2::scale_x_discrete(limits = as.character(1:2)) +
    # ggplot2::scale_y_continuous(breaks = 5:10) +
    ggplot2::labs(x = "First Interval",
                  y = "Second Interval",
                  fill = "Number of\nSongs") +
    ggplot2::theme_bw() +
    scale_fill_tvc_c(na.value = "white")
}
