# WARNING - Generated by {fusen} from dev/flat_plot_tvc_histogram.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Occurences Histogram
#'
#' @param songs a tibble with at least a column `Album_Year`, `Song` and `ISRC`.
#'
#' @return \code{plot_tvc_histogram} returns a plot
#' @export
#'
#' @importFrom ggplot2 ggplot aes geom_histogram theme_bw labs
#' @examples
#' songs <- tibble::tibble(Song = paste("Love Me", 1:30L, "Times"),
#'                         ISRC = sample(c(letters, LETTERS), size = 30L, replace = FALSE),
#'                         genres = purrr::map(1:30L,
#'                                             .f = ~ sample(x = c("rock", "metal",
#'                                                                 "classical", "pop",
#'                                                                 "yacht rock"),
#'                                                           size = 2)),
#'                         Album_Year = round(rnorm(n = 30L,
#'                                                  mean = 1986,
#'                                                  sd = 7)))
#' songs %>% 
#'   plot_tvc_histogram()
plot_tvc_histogram <- function(songs) {
  songs %>% 
    ## Remove classical music
    dplyr::group_by(ISRC) %>% 
    dplyr::filter(!any(purrr::map_lgl(.x = genres, .f = ~ "classical" %in% .x))) %>% 
    dplyr::ungroup() %>% 
    ## Keep one element per SOng, ISRC
    dplyr::distinct(Song, ISRC, Album_Year, .keep_all = TRUE) %>% 
    ggplot2::ggplot() +
    ggplot2::aes(Album_Year) +
    ggplot2::geom_histogram(binwidth = 1) +
    ggplot2::annotate(geom = "label", x = c(1986, 2025), y = 5, label = c("1986", "2025")) +
    ggplot2::theme_bw() +
    ggplot2::labs(x = "Album Year",
                  y = "Number of Songs",
                  title = "Occurences of VCT through History")
}
