# WARNING - Generated by {fusen} from dev/flat_get_spotify_api_playlist.Rmd: do not edit by hand # nolint: line_length_linter.

#' Query Playlist
#' 
#' Description
#' 
#' @return
#' 
#' @noRd
#' @examples
#' query_playlist()
query_playlist <- function(url, params) {
  res <- httr::RETRY(
    verb = "GET",
    url = url,
    query = params[1:2],
    config = httr::add_headers(
      Authorization = paste("Bearer", params$access_token)
    ),
    encode = "json"
  )
  httr::stop_for_status(res)
  res <- jsonlite::fromJSON(
    httr::content(res, as = "text", 
                  encoding = "UTF-8"),
    flatten = TRUE
    )
  res
}
