# WARNING - Generated by {fusen} from dev/flat_read_sheet_triad.Rmd: do not edit by hand # nolint: line_length_linter.

#' Read Googlesheet Triad
#'
#' @return \code{read_sheet_triad} returns a tibble with triad information
#' @export
#' @importFrom googlesheets4 read_sheet
#'
#' @examples
#' triads <- read_sheet_triad()
read_sheet_triad <- function() {
  keysAPI <- get_config(env = "google")
  ss <- keysAPI[["base_url"]]
  sheet <- keysAPI[["triade_sheet"]]
  data <- googlesheets4::read_sheet(
    ss = ss,
    sheet = sheet
  )
  return(data)
}
