# WARNING - Generated by {fusen} from dev/flat_scale_palette_triad.Rmd: do not edit by hand # nolint: line_length_linter.

#' Discrete Colour Scale
#' 
#' Description
#' @param palette either gradient or "main" or ?
#' @param direction 1 for onward or -1 for downward
#' @param ... other params ?
#' 
#' @return \code{scale_colour_tvc_d} returns the discrete tvc colour palette for points and lines.
#' 
#' @export
#' @examples
#' scale_colour_tvc_d()
scale_colour_tvc_d <- function(palette = "main", direction = 1, ...) {

  ggplot2::discrete_scale(
    aesthetics = "colour",
    scale_name = "tvc",
    palette_gen_d(palette, direction),
    ...
  )
}
