# WARNING - Generated by {fusen} from dev/flat_scale_palette_triad.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @param palette either gradient or "main" or ?
#' @param direction 1 for onward or -1 for downward
#' @param ... other params ?
#'
#' @return \code{scale_colour_tvc_c} returns a corporate palette
#' 
#' @export
#' @importFrom ggplot2 scale_colour_gradientn
#' @examples
#' scale_colour_tvc_c()
scale_colour_tvc_c <- function(palette = "gradient", direction = 1, ...) {

  pal <- palette_gen_c(palette = palette, direction = direction)

  ggplot2::scale_colour_gradientn(colors = pal(256), ...)

}
