# WARNING - Generated by {fusen} from dev/flat_scale_palette_triad.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @return \code{tvc_corp_palette} returns a corporate palette based on Vanessa Carlton debut album "Be Not Nobody".
#' 
#' @noRd
#' @examples
#' tvc:::tvc_corp_palette()
tvc_corp_palette <- function(palette = "main", ...) {

  tvc_corp_palettes <- list(
    `main` = c("#EB5646",  # Rouge vif
               "#FCF1DD",  # Beige clair
               "#D9A066",  # Ocre dore, pour rechauffer et varier
               "#A3472A",  # Terre cuite foncee, plus rustique
               "#7B2E2E", # Bordeaux profond, pour l’ancrage visuel,
               "black"),  # Noir,  
    `gradient` = c("#FCF1DD",  # Beige clair
                   "#D9A066",  # Ocre dore, pour rechauffer et varier
                   "#A3472A",  # Terre cuite foncee, plus rustique
                   "#EB5646")  # Rouge vif
  )

  tvc_corp_palettes[[palette]]
}
