# WARNING - Generated by {fusen} from dev/flat_write_missing_region.Rmd: do not edit by hand # nolint: line_length_linter.

#' Write Missing Region
#'
#' @param songs a tibble of songs x artists as returned by \code{\link{get_spotify_api_playlist}}
#'
#' @return \code{write_missing_region} write new artists with missing region in the triad google sheet. 
#' @export
#'
#' @examples
#' # write_missing_region(songs)
write_missing_region <- function(songs) {
  regions <- googlesheets4::read_sheet(
    ss = get_config("google")$base_url,
    sheet = "Regions"
  )
  
  songs %>%
    dplyr::distinct(Artist, genres) %>%
    # dplyr::distinct(genres, .keep_all = TRUE) %>% View()
    dplyr::arrange(Artist) %>%
    dplyr::mutate(Region = dplyr::case_when(
      purrr::map_lgl(genres, .f = ~ any(c("chanson", "french jazz", "vari\u00e9t\u00e9 fran\u00c7aise", "french pop") %in% .x)) ~ "France",
      purrr::map_lgl(genres, .f = ~ any(c("celtic") %in% .x)) ~ "Ireland",
      purrr::map_lgl(genres, .f = ~ "swedish pop" %in% .x) ~ "Sweden",
      purrr::map_lgl(genres, .f = ~ "norwegian pop" %in% .x) ~ "Norway",
      purrr::map_lgl(genres, .f = ~ "k-ballad" %in% .x) ~ "South Korea",
      TRUE ~ as.character(NA)
    )) %>%
    dplyr::anti_join(regions, by = dplyr::join_by(Artist)) %>%
    dplyr::mutate(genres = purrr::map_chr(genres, .f = ~ paste(.x, collapse = ", "))) %>%
    as.data.frame() %>%
    googlesheets4::write_sheet(ss = get_config("google")$base_url, sheet = "New Regions")
}
